FROM python:3.10

WORKDIR /app

COPY . /app

RUN pip install streamlit neo4j pandas matplotlib streamlit-autorefresh

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
